version: '3.3'
services:

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "test"
    ports:
      - '5433:5432'